steps:
  - id: 'Setup Buckets'
    name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: 'sh'
    args:
      - ./buckets.sh
    env:
      - PROJECT_ID=${_PROJECT_ID}

  - id: 'Pre-terraform'
    name: 'gcr.io/cloud-builders/gcloud-slim'
    entrypoint: 'sh'
    args:
      - ./preTerraform.sh
    env:
      - BRANCH_NAME=${_BRANCH_NAME}
      - PROJECT_ID=${_PROJECT_ID}
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=sa-terraform@${_PROJECT_ID}.iam.gserviceaccount.com

  - id: 'Terraform Common'
    name: 'hashicorp/terraform:1.2.3'
    entrypoint: 'sh'
    args:
      - ./terraform.sh
    env:
      - BRANCH_NAME=${_BRANCH_NAME}
      - PROJECT_ID=${_PROJECT_ID}
      - GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=sa-terraform@${_PROJECT_ID}.iam.gserviceaccount.com

logsBucket: "gs://${_PROJECT_ID}-build-reports/build-logs/infra"
options:
  logging: GCS_ONLY
timeout: 1800s
